runtime: php81  # Utilise PHP 8.1, adapte si besoin
entrypoint: serve index.html  # Si l'entrée principale est un fichier HTML, sinon utilise index.php

handlers:
  - url: /.*
    script: auto

env_variables:
  APP_ENV: production

