name: Deploy Code2Gen to Google Cloud
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Lister les fichiers dans le dépôt pour vérifier l'arborescence
      - name: List files in repository
        run: ls -R

      # Étape 3 : Installer Google Cloud SDK (version mise à jour)
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # Étape 4 : Déployer sur App Engine
      - name: Deploy to App Engine
        run: |
          gcloud app deploy app.yaml --quiet

