name: Deploy Code2Gen to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Authentification avec Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Étape 3 : Configurer le SDK Google Cloud
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Étape 4 : Déployer sur App Engine
      - name: Deploy to App Engine
        run: |
          cd code2Gen   # Aller dans le dossier de l'application
          gcloud app deploy app.yaml --quiet
